# Personal Site Settings
title: Gabriel Lopez, PhD
description: "Co-founder & CEO of Synvivia. Exploring synthetic biology, AI, and the future of biopharmaceutical manufacturing."
author: Gabriel Lopez

# Contact & Social Links
# Leave the value empty ("") for any links you don't want to display yet.
email: "x@y.com"
github_username: "DNA2RNA" # The theme might use this, so it's good to keep.
linkedin_url: ""

# Theme Settings
#remote_theme: broccolini/swiss
#theme_color: blue
# ----------------------------------------------------
# THEME SETTING - THIS IS THE ONLY MAJOR CHANGE
# ----------------------------------------------------
theme: minima

# Build settings (DO NOT CHANGE)
url: "https://DNA2RNA.github.io"
baseurl: ""
