# -----------------------------------------------------------------------------
# Site Settings (Personal)
# -----------------------------------------------------------------------------
# These settings define your personal brand for the site.

title: Gabriel Lopez, PhD
description: "Co-founder & CEO of Synvivia. Exploring synthetic biology, AI, and the future of biopharmaceutical manufacturing."
author: Gabriel Lopez

# -----------------------------------------------------------------------------
# Contact & Social Links
# -----------------------------------------------------------------------------
# Add your personal social/professional links here.

# email: your-personal-email@example.com # IMPORTANT: Replace with your contact email
# github_username: DNA2RNA
# linkedin_url: "https://www.linkedin.com/in/your-profile-url/" # IMPORTANT: Add your personal LinkedIn URL
# twitter_username: YourTwitterHandle  # Uncomment and add your Twitter if you use it

# -----------------------------------------------------------------------------
# Build Settings (Technical)
# -----------------------------------------------------------------------------
# These are correctly set for your site. No changes needed here.

url: "https://DNA2RNA.github.io"
baseurl: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# -----------------------------------------------------------------------------
# Theme Settings
# -----------------------------------------------------------------------------
# This tells Jekyll to use the Swiss theme.

remote_theme: broccolini/swiss
theme_color: white
