# Personal Site Settings
title: Gabriel Lopez, PhD
description: "Co-founder & CEO of Synvivia. Exploring synthetic biology, AI, and the future of biopharmaceutical manufacturing."
author: Gabriel Lopez

# Contact & Social Links
# email: your-personal-email@example.com # <-- EDIT THIS
# github_username: DNA2RNA
# linkedin_url: "https://www.linkedin.com/in/your-profile-url/" # <-- EDIT THIS

# Theme Settings
remote_theme: broccolini/swiss
theme_color: blue

# Build settings (DO NOT CHANGE)
url: "https://DNA2RNA.github.io"
baseurl: ""
